version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  mssql-db-services-api:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_services_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "mypassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data_services:/var/opt/mssql

  mssql-db-authorization-api:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_authorization_container
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "mypassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data_authorization:/var/opt/mssql

  mssql-db-documents-api:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_documents_container
    ports:
      - "1436:1433"
    environment:
      SA_PASSWORD: "mypassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data_documents:/var/opt/mssql
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: my-rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
    
  postgressql-db-appointments-api:
    image: postgres:15
    container_name: postgresql_appointments_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword123!
      POSTGRES_DB: appointmentsdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  mssql-db-profiles-api:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_profiles_container
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "mypassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data_profiles:/var/opt/mssql

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

volumes:
  postgres_data:
  mssql_data_services:
  mssql_data_authorization:
  mssql_data_documents:
  mssql_data_profiles:
