name: CI Pipeline Action
description: Build, restore, and test project
inputs:
    project:
        description: 'Project folder name'
        required: true
    solution:
        description: 'Solution folder name'
        required: true
    tests_project:
        description: 'Project tests folder name'
        required: false
runs:
    using: "composite"
    steps:
        - name: Cache NuGet packages
          uses: actions/cache@v3
          with:
              path: ~/.nuget/packages
              key: ${{ github.os }}-nuget-${{ inputs.project }}
              restore-keys: |
                  ${{ github.os }}-nuget-

        - name: Restore and Build Project
          run: |
              dotnet restore ${{ inputs.solution }}/${{ inputs.project }}/${{ inputs.project }}.csproj
              dotnet build ${{ inputs.solution }}/${{ inputs.project }}/${{ inputs.project }}.csproj --no-restore --configuration Release
          shell: bash

        - name: Run Tests (if tests_project is set)
          if: ${{ inputs.tests_project != '' }}
          run: |
              dotnet test ${{ inputs.solution }}/${{ inputs.tests_project }}/${{ inputs.tests_project }}.csproj
          shell: bash
