name: CI Pipeline Action
description: Build, restore, and test project
inputs:
    project:
        description: 'Project name'
        required: true
runs:
    using: "composite"
    steps:
        - name: Cache NuGet packages
          uses: actions/cache@v3
          with:
              path: ~/.nuget/packages
              key: ${{ github.os }}-nuget-${{ inputs.project }}
              restore-keys: |
                  ${{ github.os }}-nuget-

        - name: Restore, Build, and Run Tests
          run: |
              dotnet restore ${{ inputs.project }}/${{ inputs.project }}.API/${{ inputs.project }}.API.csproj
              dotnet build ${{ inputs.project }}/${{ inputs.project }}.API/${{ inputs.project }}.API.csproj --no-restore --configuration Release
              dotnet test ${{ inputs.project }}/${{ inputs.project }}.Tests/${{ inputs.project }}.Tests.csproj
          shell: bash
