name: CI Pipeline

on:
    workflow_call:
        inputs:
            project:
                description: 'Project name'
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and Test Project

        steps:
          - name: Cache NuGet packages
            uses: actions/cache@v3
            with:
                path: ~/.nuget/packages
                key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
                restore-keys: |
                    ${{ runner.os }}-nuget-

          - name: Restore, Build, and Run Tests
            run: |
              dotnet restore ${{ inputs.project }}/${{ inputs.project }}.API/${{ inputs.project }}.API.csproj
              dotnet build ${{ inputs.project }}/${{ inputs.project }}.API/${{ inputs.project }}.API.csproj --no-restore --configuration Release
              dotnet test ${{ inputs.project }}/${{ inputs.project }}.Tests/${{ inputs.project }}.Tests.csproj
