name: CI Pipeline

on:
  push:
    paths: 
      - Services/**
  pull_request:
    paths: 
      - Services/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Services API
      - name: Restore, Build and Run Tests Services API project
        run: |
          dotnet restore Services/Services.API/Services.API.csproj
          dotnet build Services/Services.API/Services.API.csproj --no-restore --configuration Release
          dotnet test Services/Services.Tests/Services.Tests.csproj
