name: CI for Offices

on:
    push:
        paths:
        - "Offices/**"

jobs:
    trigger-ci-pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger CI Pipeline
              uses: ./.github/actions/ci-pipeline
              with:
                  project: 'Offices'

    trigger-style-checker:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Style Checker
              uses: ./.github/actions/style-checker
              with:
                  project: 'Offices'
