name: CI for React client
on:
  push:
    paths:
      - "react-client/**"

jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: react-client
        run: npm ci

      - name: Run Prettier
        working-directory: react-client
        run: npm run format

      - name: Run ESLint
        working-directory: react-client
        run: npm run lint

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./react-client

      - name: Run Jest Unit Tests
        run: npm run test -- --ci --coverage
        working-directory: ./react-client

      - name: Install Cypress dependencies
        run: npx cypress install
        working-directory: ./react-client

      - name: Start server
        run: npm run dev &
        working-directory: ./react-client
        env:
          NODE_ENV: test

      - name: Wait for server to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: "http://localhost:3000"
          timeout: 30

      - name: Run Cypress E2E Tests
        run: npx cypress run
        working-directory: ./react-client