name: CI for react client
on:
  push:
    paths:
    - "react-client/**"
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: npm install eslint prettier
      - name: Prettier
        run: npm run format
      - name: Lint
        run: npm run lint