    inspection:
      runs-on: ubuntu-latest
      name: Inspect Code Services
      needs: cleanup

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 8.x

        - name: Restore Dependencies
          run: dotnet restore Services/Services.sln

        - name: Inspect code
          uses: muno92/resharper_inspectcode@1.11.8
          with:
            solutionPath: ./Services/Services.sln
            failOnIssue: 1
            minimumSeverity: notice
            solutionWideAnalysis: true