name: CI for Services

on:
    push:
        paths:
        - "Services/**"

jobs:
    trigger-ci-pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger CI Pipeline
              uses: ./.github/actions/ci-pipeline
              with:
                  project: 'Services'

    trigger-style-checker:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Style Checker
              uses: ./.github/actions/style-checker
              with:
                  project: 'Services'
