name: ReSharper CLI CleanupCode Services

on: [ push ]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Cleanup And Inspect Code Services

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore Services/Services.sln
          
      - name: Cleanup Code
        id: cleanup
        uses: ArturWincenciak/ReSharper_CleanupCode@v3.0
        with:
          solution: 'Services/Services.sln'
          fail_on_reformat_needed: 'yes'
          jb_cleanup_code_arg: '--verbosity=INFO --editorconfig=./.editorconfig'

      - name: Inspect code
        uses: muno92/resharper_inspectcode@1.11.8
        with:
          solutionPath: ./Services/Services.sln
          failOnIssue: 1
          minimumSeverity: notice
          solutionWideAnalysis: true
          additionalArguments: '--editorconfig=./.editorconfig'